#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "pcdapi.h"
#include "example_rules.h"

int main( int argc, char *argv[] )
{
	int val;
	/* Declare a rule id to be used later. The Macro and definitions
	 * are generated by the pcdparser utility */
	EXAMPLES_DECLARE_PCD_RULEID( ruleId, EXAMPLES_PCD_RULE_H );

	/* This is a different way to do the same as above:
	 *
	 * PCD_DECLARE_RULEID( ruleId, "EXAMPLES", "H" );
	 */

	/* Register to the PCD's exception handlers */
	PCD_API_REGISTER_EXCEPTION_HANDLERS();

	printf( "Application 'g' started, initializing...\n" );

	/* Initializing stuff */
	if( argc > 1 )
		val = atoi(argv[1]);
	else
		val = 0;

	printf( "'g' init done, val = %d\n", val );
	printf( "'g' is sending PROCESS READY event to the PCD...\n" );

	/* Sending PROCESS READY event to the PCD */
	if( PCD_api_send_process_ready() != 0 )
	{
		printf( "Failed to send ready event!" );
		exit(1);
	}

	printf( "'g' is doing some work..." );

	/* Do some "work" */
	while(val--)
	{
		sleep(1);
	}

	while(1)
	{
		printf ( "'g' has decided its time to start process 'h' manually. Request PCD to start it now.\n");

		/* Start a application h manually */
		if( PCD_api_start_process( &ruleId, NULL ) != 0 )
		{
			printf( "Failed to start a new process!\n" );
			exit(1);
		}

		printf( "'g' is doing some more work..." );
		val = 10;

		/* Do some "work" */
		while(val--)
		{
			sleep(1);
		}

		printf ( "'g' has decided its time to terminate process 'h' manually. Request PCD to terminate it now.\n");

		/* Start a application h manually */
		if( PCD_api_terminate_process( &ruleId ) != 0 )
		{
			printf( "Failed to terminate process!\n" );
			exit(1);
		}

		printf( "'g' is doing some more work..." );
		val = 10;

		/* Do some "work" */
		while(val--)
		{
			sleep(1);
		}
	}
	return 0;
}
